#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# study_with_python documentation build configuration file, created by
# sphinx-quickstart on Mon Jan 22 20:32:16 2018.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os, sys
sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.abspath('../'))
sys.path.insert(0, os.path.abspath('../src'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

"""
拡張モジュール
"""
extensions = [
    'sphinx.ext.autodoc',       # apiドキュメントを自動生成
    'sphinx.ext.githubpages',   # Github Pagesに公開するための設定群
    'sphinx.ext.viewcode',      # ソースコードを描画する
    'sphinx.ext.graphviz',      # グラフを書く

    # matplotlib.sphinxextのセット
    'matplotlib.sphinxext.mathmpl',
    'matplotlib.sphinxext.only_directives',
    'matplotlib.sphinxext.plot_directive',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'study_with_python'
copyright = '2018, murnana'
author = 'murnana'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.0.0'
# The full version, including alpha/beta/rc tags.
release = '0.0.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'ja'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
    'theme/*',
    'api/modules.rst'
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for Graphviz -------------------------------------------------

graphviz_output_format = 'svg'


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'python_docs_theme'
html_theme_path = ['./theme']

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'root_name': 'Pythonの勉強',
    'root_url': 'https://murnana.github.io/study-with-python/',
    'root_include_title': False
}

# 追加のテンプレート(もしくは組み込みのテーマに関するテンプレートをオーバーライトするテンプレート)が含まれているパスのリストです。
# 設定ディレクトリからの相対パスで設定します。
#
# バージョン 1.3 で変更: これらのファイルは自動的に exclude_patterns に追加され、ビルドの対象にはなりません。
templates_path = ['_templates']


# -- Options for LaTeX output ---------------------------------------------

"""
The LaTeX engine to build the docs. The setting can have the following values:

    - 'pdflatex' -- PDFLaTeX (default)
    - 'xelatex' -- XeLaTeX
    - 'lualatex' -- LuaLaTeX
    - 'platex' -- pLaTeX (default if language is 'ja')
"""
latex_engine = 'platex'



"""
この値はドキュメントツリーをどのようにグループ化してLaTeXソースに含めるか決定します。
これは、 (startdocname, targetname, title, author, documentclass, toctree_only)
というタプルのリストでなければなりません。
"""
latex_documents = [(
    master_doc,                             # startdocname
    'study_with_python.tex',                # targetname
    'study\\_with\\_python Documentation',  # title
    'murnana',                              # author
    'manual',                               # documentclass
    True,                                   # toctree_only
),]

"""
'howto' と 'manual' から実際にSphinxのクラスとして使われる
document classへのマッピングをする辞書です。
デフォルトでは 'howto' には 'article', 'manual' には 'report' が使われます。

バージョン 1.5 で変更:
    In Japanese docs (language is 'ja'),
    by default 'jreport' is used for 'howto' and 'jsbook' for 'manual'.
"""
latex_docclass = {
    'manual': 'jsbook',
    'howto': 'jreport',
}

# -- sphinx.ext.imgmath -- 数式を画像にレンダリングします ---------------------
"""
出力する画像のフォーマット。
デフォルトは 'png' です。 'png' または 'svg' のいずれかの値をとります。
"""
imgmath_image_format = 'svg'

# """
# 数式のコード片を変換するのに使用する、
# 短いLaTeXファイルの中の前置きとして入れる、
# 追加のLaTeXコードです。
# デフォルトでは空です。
# このオプションは、例えば、
# 数式の中で使いたいコマンドのためのパッケージを追加するのに使えます。
# """
# imgmath_latex_preamble = []

